### ISSUE TITLE
LinkedSecret.security.kubeideas.io "xxx" is invalid: spec.providerSecretFormat: Required value

### ISSUE THREAD

**Issue by neoemu** [kubeideas/linkedsecrets#6]
Hello Tolentino

I did the installation via helm following the tutorial and i am taking an error when i create linkedsecret.

obs: installing linkedsecrets in the latest version (v.0.8.3) on my test cluster aws eks 1.21.5

example linked secret yaml:

```
apiVersion: security.kubeideas.io/v1
kind: LinkedSecret
metadata:
  name: teste-lns
spec:
  keepSecretOnDelete: true
  provider: AWS
  providerSecretFormat: JSON
  providerOptions:
    secret: prod/mysecret
    region: us-east-2
    version: AWSCURRENT
  secretName: testelns
  schedule: "@every 10m"
  suspended: false
```

and I'm getting this error talking about providerSecretFormat:

`1.6604332632654967e+09	DEBUG	controllers.LinkedSecret	BEGIN RECONCILING - FINILIZER LINKEDSECRET	{"linkedsecret": "default/teste-lns"}
1.6604332632785416e+09	ERROR	controller.linkedsecret	Reconciler error	{"reconciler group": "security.kubeideas.io", "reconciler kind": "LinkedSecret", "name": "teste-lns", "namespace": "default", "error": "LinkedSecret.security.kubeideas.io \"teste-lns\" is invalid: spec.providerSecretFormat: Required value"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227`

but strange is that I'm passing the JSON parameter as we saw above in my yaml example.

the secret I'm using: 

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/3679091/184516235-b626316f-ea61-4575-8546-cf3cd34b2642.png">

I reviewed the linkedsecrets installation but I didn't find anything that could have any connection with it, I don't know if you already got this error and if you could help, thank you.
